### ISSUE TITLE
Migration to https://github.com/varigit/meta-variscite-fslc

### ISSUE THREAD

**Issue by floion** [varigit/meta-variscite-mx6#7]
Hi,
I see this layer received updates (in the sumo branch) and also contains the BSP for the imx8m machines. Is there any plan on moving the imx8m to the newer repository (https://github.com/varigit/meta-variscite-fslc) ?
Why is this separation for?

**Comment by eranmati** [comment]
Hi Florin.
meta-variscite-imx is used with official NXP Yocto releases, and meta-variscite-fslc is used with the FSL Community BSP.

While we have moved from the NXP official releases to the community based BSP for the mx6, mx6ul & mx7, we currently use the official NXP releases for the mx8 platforms, since they are still new platforms.

Please see:
http://variwiki.com

Regards,
Eran
